apiVersion: v1
kind: Secret
metadata:
    name: sqlserver-connection-string
    namespace: prod-tour-of-heroes
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:7djJo7sXEVyZMJMuM93elb9l1cXe/UIIzehRtZVz+9v36GW4O1vHu4KCxulyonpY5a0wPO2luRnc7SUDSl/X1Ay2kVFy3oNXuLUf4e22ocSMn5ah+JyqHDS+mRS0JiThw8nATEeajAM2ZOwzyR4fMLKehjXs76ejR2iqXl4T6w==,iv:UEN/DlwTHWnxtzT3SikfeQoug//XM84lM6LFvgDSs6Y=,tag:8NcgEvM5sT4mw62cmbqWYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-19T17:01:01Z"
    mac: ENC[AES256_GCM,data:99Qk7g9eODTNnMgYc+daLuS0aA90GIETQUwMdjJ0rwg5tQIYt+AEHapUbwpG2EEQ9DA6UukJqVVPldmLREveotKoCOPNdNuZFWkrvI20jNj5W8B3l7GtKdpup3H0HKvNVJU5c5a3L6k45x3kwdmdhGE9aOF3/3IWAt1dsYngynw=,iv:hqzIlz5nuYTmRhuSK5BGnIjRWCYBXq1UDchYPN1+jvE=,tag:fddfvn5xsdELh5bD20y5OQ==,type:str]
    pgp:
        - created_at: "2022-04-19T17:01:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9YE9b+MZ3xCAQ//bGylP7C3Aov+3cB4QZ1xCI2dCDN6Me0nAUzbAhtFvVWB
            pSGm7QHffAWlgGIkop2x/5+LdQPS4x1e1qld/KxPAuG2ZM/9wuEpifvBLow6MCfF
            Cd0FUQT9XlWdiIQ6rN59t7H5c+Grp8wmwHh9aAqTPr4qD8kkq0hj/crZYRz1gDdC
            8YpcYQxH4HiyNMZiWNNnFYP745P3mAQrWiZ9b2D5Q9W8lLvDoXt2xPkDYYDMarIJ
            iAX533+bFC4TLeDHVkTvcj2XT+kYt1EZoaa/r9NfEU4/vgFPFPQZQf8OgcWjGVCZ
            A/KVIfW2qBg3gLP9R5cnzcgBrQ0wY5k2xgbgyMF2ZqV6zzgI+dFr97AI6hMnHEIq
            DN0asvxGnVtD6EAHvIjfUQ7rPjBUBNYinwTcOKBG/R7h+eimJ1iIGpvQkPgW41GZ
            cxKmVFCiK6C7jPYiF2Vh0riy0Db0cqq1BlmQI9n0kDOxOoC8Iq4msRKEPtriQhkx
            91uEvGVsZLusoJg/cnyjXycMSANhdIJ1+KM8rwrFvhChavv3oCMb2ScFch5Zo/NC
            dx8hePlTXcm9lkZV/LWNnPW/CgsFIvMtX4PRK1oovtQLvTSVbCP5Id4t3oJANaFp
            Gkl4oz0lkNLhyUfQDnuDQYnwc2uH61tMb0UUVRtKq7tV5QsP3KAg7VlkDgW64mHU
            ZgEJAhD+Xn4P0wQpp7ajxBmXZlHOU5g9sC//bmN3g5XWWDrRwj3G3koMDYdMcGe7
            M4GXpvxqAZLLH58Dje+ur9nLorsXyUDh3LzKjCX8skOnPPjVkbWZ6neuSgIYO2l+
            a5nIkKwIsw==
            =BwK8
            -----END PGP MESSAGE-----
          fp: FE72F1D7FAA1B9CE6B1DA8E3DD7542BD4614B58D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
