apiVersion: v1
kind: Secret
metadata:
  name: app-insights-secret
type: Opaque
data:
  connection_string: SW5zdHJ1bWVudGF0aW9uS2V5PWVjNWY0MjI2LTI4MmItNDBhNS1hYTA5LWZlODRjOTdhOThkNDtJbmdlc3Rpb25FbmRwb2ludD1odHRwczovL25vcnRoZXVyb3BlLTAuaW4uYXBwbGljYXRpb25pbnNpZ2h0cy5henVyZS5jb20vO0xpdmVFbmRwb2ludD1odHRwczovL25vcnRoZXVyb3BlLmxpdmVkaWFnbm9zdGljcy5tb25pdG9yLmF6dXJlLmNvbS8=
