apiVersion: v1
kind: Service
metadata:
  labels:
    app: tour-of-heroes-api
  name: tour-of-heroes-api
spec:
  type: NodePort
  
  ports:
  - name: web
    port: 80
    targetPort: 5000
    nodePort: 30080
  selector:
    app: tour-of-heroes-api
