apiVersion: v1
kind: Service
metadata:
  name: {{ include "tour-of-heroes-helm.fullname" . }}
  labels:
    {{- include "tour-of-heroes-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}  
  ports:
    - port: {{ .Values.service.port }}    
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tour-of-heroes-helm.selectorLabels" . | nindent 4 }}   
