apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-tour-of-heroes
namePrefix: dev-
patchesStrategicMerge:
- backend/deployment-patch.yaml
- db/deployment-patch.yaml
resources:
- ../../base
images:
- name: ghcr.io/0gis0/tour-of-heroes-dotnet-api/tour-of-heroes-api  
  newTag: "1234"
- name: ghcr.io/0gis0/tour-of-heroes/tour-of-heroes
  newTag: aadda92
secretGenerator:
- behavior: replace
  literals:
  - password=Server=dev-tour-of-heroes-sql,1433;Initial Catalog=heroes;Persist Security
    Info=False;User ID=sa;Password=YourStrong!Passw0rd;
  name: sqlserver-connection-string
  type: Opaque
