apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-tour-of-heroes
namePrefix: prod-
patchesStrategicMerge:
  - backend/deployment-patch.yaml
resources:
  - ../../base
images:
  - name: argocdregistry.azurecr.io/tourofheroesapi
    newTag: "1000"
