apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:  
  - deployment.yaml
  - service.yaml
  - persistent-volume.yaml
  - secret-sealed.yaml
  # - secret.enc.yaml
  # - secret.yaml

# secretGenerator:
#   - name: mssql
#     type: Opaque
#     literals:
#       - "SA_PASSWORD=YourStrong!Passw0rd"