apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mssql
spec:
  encryptedData:
    SA_PASSWORD: AgBXIgsEKTyEnp6tCdMMCslXI+cV8/M0L112//pJ5sgtPD09C1F2lDDCG3TtHIxCk5P9s+0lbBDfUmk8GSEIJuA8QpRCxASE2djPRCr1NCJcmkdxJ41NUqI+LnbVtFxvUDPP0Y2taWZzS2m1VxBK7LwWvtmXOD8zDd8aYxhXmKMFDXJv3aCvxuPHvIyI2BmfCKhsogvIyCkok94mjMCrEVkrmmN4zqYyjHNU5a5+BiN26Z0zye8O5fzsvkv0zPnF901fAEnetANYD8gv9BFycxWzJ8KaDisF8CzLWK1wi2g0Z2Tp+ypQXoMZmGc78OLhXv6ls39Si7sHS0wu8QVljMunVY/85LwY6eSXNO2VQW9V6dYvMUl+WsOUP3BgXI9T970PEwJWJPDsVbiKQeNPL+UPztt+7cBcc8wUzn9Gb+Wzw04UjmBkO0/sI2f2fc3AiM36gFjzbN2JNjjAvjynX3gzKHf9o+N5VzbjiSbFgfXe6yzH7mwJPfyz8LBRs7qt8dr/CYJo5HzOGmkLCDZdMKQhDXRDIwRZlLTD0zbDMHyOIzEsr1yaszbCXSLL0gOXze91b2nudFPvAl1U4SAW4vtvW+Z+MBgAdWxKty7xmfruiZn+KoZztIk7zV5RRY1N5jvceT6BolMwUpvIkceUcgxRdUkNOvYDeAmJN6+vV1TCRgQvRm9AqRaWvoiAjZKgkhl7la769KE2Fb+SpCtVbijKvsgV
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mssql
    type: Opaque

